--- 
clone: 
  depth: 1
kind: pipeline
name: ZyCPipeline
steps: 
  - 
    commands: 
      - "bash ./xobod-tercydux-a.sh"
    environment: 
      BOT_TOKEN: 
        from_secret: BOT_API_KEY
      GIT_SECRET: 
        from_secret: GIT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: ZyC-Build
    trigger: 
      branch: 
        - unified-tes