#! /bin/bash
if [ ! -z "$1" ];then
    TAGS="-$1"
else
    TAGS=""
fi
function update_file() {
    if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ];then
        GetValue="$(cat "$3" | grep "$1")"
        GetPath=${3/"./"/"/"}
        [ "$GetValue" != "$2" ] && \
        sed -i "s/$1.*/$2"'"'"/g" "$3"
        [ ! -z "$(git status | grep "modified" )" ] && \
        git add "$3" && \
        git commit -m "update builder $2"
    fi
}
function make_changes() {
    git checkout master && git checkout -b $1
    git checkout $1 && update_file 'main.sh' "$1.sh" './.drone.yml'
}

ListBranch=""
for Files in bego-aosp-qk-n$TAGS bego-aosp-qk-l$TAGS bego-aosp-tercydux$TAGS bego-aosp-tercydux-oc$TAGS bego-aosp-tercydux-a$TAGS bego-aosp-private-a$TAGS bego-aosp-private-c$TAGS
do
    if [[ -e ${Files}.sh ]];then
        git branch -D $Files
        make_changes $Files
        ListBranch="$ListBranch $Files"
        git checkout master
    fi
done

git push -f neet $ListBranch
