#! /bin/bash
if [ ! -z "$1" ];then
    TAGS="-rc"
else
    TAGS=""
fi
function update_file() {
    if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ];then
        GetValue="$(cat "$3" | grep "$1")"
        GetPath=${3/"./"/"/"}
        [ "$GetValue" != "$2" ] && \
        sed -i "s/$1.*/$2"'"'"/g" "$3"
        [ ! -z "$(git status | grep "modified" )" ] && \
        git add "$3" && \
        git commit -m "update builder $2"
    fi
}
function make_changes() {
    git checkout master && git checkout -b $1
    git checkout $1 && update_file 'main.sh' "$1.sh" './.drone.yml'
}

for Files in xobod-qk-ul xobod-qk-l xobod-qk-n xobod-tercydux-a xobod-tercydux-b xobod-qk-ul-gcc xobod-qk-l-gcc xobod-qk-n-gcc xobod-tercydux-a-gcc xobod-tercydux-b-gcc
do
    git branch -D $Files$TAGS
    make_changes $Files$TAGS
done

git push -f origin \
xobod-qk-ul$TAGS \
xobod-qk-l$TAGS \
xobod-qk-n$TAGS \
xobod-tercydux-a$TAGS \
xobod-tercydux-b$TAGS \
xobod-qk-ul-gcc$TAGS \
xobod-qk-l-gcc$TAGS \
xobod-qk-n-gcc$TAGS \
xobod-tercydux-a-gcc$TAGS \
xobod-tercydux-b-gcc$TAGS \
# xobod-main$TAGS \

git checkout master