#! /bin/bash
if [ ! -z "$1" ];then
    TAGS="-rc"
else
    TAGS=""
fi
function update_file() {
    if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ];then
        GetValue="$(cat "$3" | grep "$1")"
        GetPath=${3/"./"/"/"}
        [ "$GetValue" != "$2" ] && \
        sed -i "s/$1.*/$2"'"'"/g" "$3"
        [ ! -z "$(git status | grep "modified" )" ] && \
        git add "$3" && \
        git commit -m "update builder $2"
    fi
}
function make_changes() {
    git checkout master && git checkout -b $1
    git checkout $1 && update_file 'main.sh' "$1.sh" './.drone.yml'
}

ListBranch=""
for Files in xobod-df-keqing xobod-df-keqing-gcc xobod-df-mona xobod-df-mona-gcc xobod-df-fischl xobod-df-fischl-gcc xobod-qk-l xobod-qk-l-gcc xobod-qk-n xobod-qk-n-gcc xobod-qk-ul xobod-qk-ul-gcc
do
    git branch -D $Files$TAGS
    make_changes $Files$TAGS
    ListBranch="$ListBranch $Files$TAGS"
    git checkout master
done

git push -f neet $ListBranch